import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:ultrakey_ui/models/assets.dart';

enum GamepadCode {
  a(0x1000),
  b(0x2000),
  x(0x4000),
  y(0x8000),
  dpadUp(0x0001),
  dpadDown(0x0002),
  dpadLeft(0x0004),
  dpadRight(0x0008),
  start(0x0010),
  back(0x0020),
  leftThumb(0x0040),
  rightThumb(0x0080),
  leftShoulder(0x0100),
  rightShoulder(0x0200),
  guide(0x0400),
  lStick(0x8001),
  rStick(0x8002);

  final int value;
  const GamepadCode(this.value);

  static GamepadCode? fromString(String name) {
    for (final code in GamepadCode.values) {
      if (code.name == name) return code;
    }
    return null;
  }

  static GamepadCode? fromValue(int value) {
    for (final code in GamepadCode.values) {
      if (code.value == value) return code;
    }
    return null;
  }

  static List<String> makeIdTable() {
    return GamepadCode.values.map((e) => e.name).toList();
  }

  static Map<String, Image> icons = {
    "a": aFilledImage,
    "b": bFilledImage,
    "x": xFilledImage,
    "y": yFilledImage,
    "dpadUp": dpadUpImage,
    "dpadDown": dpadDownImage,
    "dpadLeft": dpadLeftImage,
    "dpadRight": dpadRightImage,
    "start": menuImage,
    "back": viewImage,
    "leftThumb": leftJoystickPressImage,
    "rightThumb": rightJoystickPressImage,
    "leftShoulder": leftBumperImage,
    "rightShoulder": rightBumperImage,
  };

  static Map<String, int> idMapping = {
    "dpadUp": dpadUp.value,
    "dpadDown": dpadDown.value,
    "dpadLeft": dpadLeft.value,
    "dpadRight": dpadRight.value,
    "start": start.value,
    "back": back.value,
    "leftThumb": leftThumb.value,
    "rightThumb": rightThumb.value,
    "leftShoulder": leftShoulder.value,
    "rightShoulder": rightShoulder.value,
    "a": a.value,
    "b": b.value,
    "x": x.value,
    "y": y.value,
  };

  static List<String> idTable = icons.keys.toList();
}

enum VirtualKey {
  keyNone(0x00),
  keyEscape(0x01),
  key1(0x02),
  key2(0x03),
  key3(0x04),
  key4(0x05),
  key5(0x06),
  key6(0x07),
  key7(0x08),
  key8(0x09),
  key9(0x0A),
  key0(0x0B),
  keyMinus(0x0C),
  keyEquals(0x0D),
  keyBackspace(0x0E),
  keyTab(0x0F),
  keyQ(0x10),
  keyW(0x11),
  keyE(0x12),
  keyR(0x13),
  keyT(0x14),
  keyY(0x15),
  keyU(0x16),
  keyI(0x17),
  keyO(0x18),
  keyP(0x19),
  keyLeftBracket(0x1A),
  keyRightBracket(0x1B),
  keyEnter(0x1C),
  keyLeftCtrl(0x1D),
  keyA(0x1E),
  keyS(0x1F),
  keyD(0x20),
  keyF(0x21),
  keyG(0x22),
  keyH(0x23),
  keyJ(0x24),
  keyK(0x25),
  keyL(0x26),
  keySemicolon(0x27),
  keyApostrophe(0x28),
  keyGrave(0x29),
  keyLeftShift(0x2A),
  keyBackslash(0x2B),
  keyZ(0x2C),
  keyX(0x2D),
  keyC(0x2E),
  keyV(0x2F),
  keyB(0x30),
  keyN(0x31),
  keyM(0x32),
  keyComma(0x33),
  keyPeriod(0x34),
  keySlash(0x35),
  keyRightShift(0x36),
  keyKpMultiply(0x37),
  keyLeftAlt(0x38),
  keySpace(0x39),
  keyCapsLock(0x3A),
  keyF1(0x3B),
  keyF2(0x3C),
  keyF3(0x3D),
  keyF4(0x3E),
  keyF5(0x3F),
  keyF6(0x40),
  keyF7(0x41),
  keyF8(0x42),
  keyF9(0x43),
  keyF10(0x44),
  keyNumLock(0x45),
  keyScrollLock(0x46),
  keyKp7(0x47),
  keyKp8(0x48),
  keyKp9(0x49),
  keyKpMinus(0x4A),
  keyKp4(0x4B),
  keyKp5(0x4C),
  keyKp6(0x4D),
  keyKpPlus(0x4E),
  keyKp1(0x4F),
  keyKp2(0x50),
  keyKp3(0x51),
  keyKp0(0x52),
  keyKpDecimal(0x53),
  keyKpEnter(0x01C),
  keyRightCtrl(0x01D),
  keyKpDivide(0x035),
  keyRightAlt(0x038),
  keyHome(0x047),
  keyUp(0x048),
  keyPageUp(0x049),
  keyLeft(0x04B),
  keyRight(0x04D),
  keyEnd(0x04F),
  keyDown(0x050),
  keyPageDown(0x051),
  keyInsert(0x052),
  keyDelete(0x053),
  keyLeftWindows(0x05B),
  keyRightWindows(0x05C),
  keyApplication(0x05D),
  keyMouse(0x05E),
  keyMouseLb(0x05F),
  keyMouseRb(0x060),
  keyMouseMb(0x061),
  keyMouseMw(0x062),
  keyKeyboard(0x063),
  keyMax(99);

  final int value;
  const VirtualKey(this.value);

  static int fromLogicalKey(int logical) {
    return keyMap[logical] ?? -1;
  }

  static int toLogicalKey(int nonLogical) {
    return keyMap.map((a, b) => MapEntry(b, a))[nonLogical] ?? -1;
  }

  static String displayName(int nonLogical) {
    return displayMap[nonLogical]?.toUpperCase() ?? "UNKNOWN";
  }
}

final Map<int, int> keyMap = {
  kPrimaryMouseButton: VirtualKey.keyMouseLb.value,
  kSecondaryMouseButton: VirtualKey.keyMouseRb.value,
  kMiddleMouseButton: VirtualKey.keyMouseMb.value,
  LogicalKeyboardKey.tab.keyId: VirtualKey.keyTab.value,
  LogicalKeyboardKey.keyQ.keyId: VirtualKey.keyQ.value,
  LogicalKeyboardKey.keyW.keyId: VirtualKey.keyW.value,
  LogicalKeyboardKey.keyE.keyId: VirtualKey.keyE.value,
  LogicalKeyboardKey.keyR.keyId: VirtualKey.keyR.value,
  LogicalKeyboardKey.keyT.keyId: VirtualKey.keyT.value,
  LogicalKeyboardKey.keyY.keyId: VirtualKey.keyY.value,
  LogicalKeyboardKey.keyU.keyId: VirtualKey.keyU.value,
  LogicalKeyboardKey.keyI.keyId: VirtualKey.keyI.value,
  LogicalKeyboardKey.keyO.keyId: VirtualKey.keyO.value,
  LogicalKeyboardKey.keyP.keyId: VirtualKey.keyP.value,
  LogicalKeyboardKey.keyA.keyId: VirtualKey.keyA.value,
  LogicalKeyboardKey.keyS.keyId: VirtualKey.keyS.value,
  LogicalKeyboardKey.keyD.keyId: VirtualKey.keyD.value,
  LogicalKeyboardKey.keyF.keyId: VirtualKey.keyF.value,
  LogicalKeyboardKey.keyG.keyId: VirtualKey.keyG.value,
  LogicalKeyboardKey.keyH.keyId: VirtualKey.keyH.value,
  LogicalKeyboardKey.keyJ.keyId: VirtualKey.keyJ.value,
  LogicalKeyboardKey.keyK.keyId: VirtualKey.keyK.value,
  LogicalKeyboardKey.keyL.keyId: VirtualKey.keyL.value,
  LogicalKeyboardKey.keyZ.keyId: VirtualKey.keyZ.value,
  LogicalKeyboardKey.keyX.keyId: VirtualKey.keyX.value,
  LogicalKeyboardKey.keyC.keyId: VirtualKey.keyC.value,
  LogicalKeyboardKey.keyV.keyId: VirtualKey.keyV.value,
  LogicalKeyboardKey.keyB.keyId: VirtualKey.keyB.value,
  LogicalKeyboardKey.keyN.keyId: VirtualKey.keyN.value,
  LogicalKeyboardKey.keyM.keyId: VirtualKey.keyM.value,
  LogicalKeyboardKey.escape.keyId: VirtualKey.keyEscape.value,
  LogicalKeyboardKey.digit1.keyId: VirtualKey.key1.value,
  LogicalKeyboardKey.digit2.keyId: VirtualKey.key2.value,
  LogicalKeyboardKey.digit3.keyId: VirtualKey.key3.value,
  LogicalKeyboardKey.digit4.keyId: VirtualKey.key4.value,
  LogicalKeyboardKey.digit5.keyId: VirtualKey.key5.value,
  LogicalKeyboardKey.digit6.keyId: VirtualKey.key6.value,
  LogicalKeyboardKey.digit7.keyId: VirtualKey.key7.value,
  LogicalKeyboardKey.digit8.keyId: VirtualKey.key8.value,
  LogicalKeyboardKey.digit9.keyId: VirtualKey.key9.value,
  LogicalKeyboardKey.digit0.keyId: VirtualKey.key0.value,
  LogicalKeyboardKey.minus.keyId: VirtualKey.keyMinus.value,
  LogicalKeyboardKey.equal.keyId: VirtualKey.keyEquals.value,
  LogicalKeyboardKey.backspace.keyId: VirtualKey.keyBackspace.value,
  LogicalKeyboardKey.bracketLeft.keyId: VirtualKey.keyLeftBracket.value,
  LogicalKeyboardKey.bracketRight.keyId: VirtualKey.keyRightBracket.value,
  LogicalKeyboardKey.enter.keyId: VirtualKey.keyEnter.value,
  LogicalKeyboardKey.controlLeft.keyId: VirtualKey.keyLeftCtrl.value,
  LogicalKeyboardKey.comma.keyId: VirtualKey.keyComma.value,
  LogicalKeyboardKey.period.keyId: VirtualKey.keyPeriod.value,
  LogicalKeyboardKey.slash.keyId: VirtualKey.keySlash.value,
  LogicalKeyboardKey.shiftRight.keyId: VirtualKey.keyRightShift.value,
  LogicalKeyboardKey.altLeft.keyId: VirtualKey.keyLeftAlt.value,
  LogicalKeyboardKey.space.keyId: VirtualKey.keySpace.value,
  LogicalKeyboardKey.capsLock.keyId: VirtualKey.keyCapsLock.value,
  LogicalKeyboardKey.semicolon.keyId: VirtualKey.keySemicolon.value,
  LogicalKeyboardKey.quote.keyId: VirtualKey.keyApostrophe.value,
  LogicalKeyboardKey.backquote.keyId: VirtualKey.keyGrave.value,
  LogicalKeyboardKey.shiftLeft.keyId: VirtualKey.keyLeftShift.value,
  LogicalKeyboardKey.backslash.keyId: VirtualKey.keyBackslash.value,
  LogicalKeyboardKey.f1.keyId: VirtualKey.keyF1.value,
  LogicalKeyboardKey.f2.keyId: VirtualKey.keyF2.value,
  LogicalKeyboardKey.f3.keyId: VirtualKey.keyF3.value,
  LogicalKeyboardKey.f4.keyId: VirtualKey.keyF4.value,
  LogicalKeyboardKey.f5.keyId: VirtualKey.keyF5.value,
  LogicalKeyboardKey.f6.keyId: VirtualKey.keyF6.value,
  LogicalKeyboardKey.f7.keyId: VirtualKey.keyF7.value,
  LogicalKeyboardKey.f8.keyId: VirtualKey.keyF8.value,
  LogicalKeyboardKey.f9.keyId: VirtualKey.keyF9.value,
  LogicalKeyboardKey.f10.keyId: VirtualKey.keyF10.value,
  LogicalKeyboardKey.numLock.keyId: VirtualKey.keyNumLock.value,
  LogicalKeyboardKey.scrollLock.keyId: VirtualKey.keyScrollLock.value,
  LogicalKeyboardKey.home.keyId: VirtualKey.keyHome.value,
  LogicalKeyboardKey.arrowUp.keyId: VirtualKey.keyUp.value,
  LogicalKeyboardKey.pageUp.keyId: VirtualKey.keyPageUp.value,
  LogicalKeyboardKey.arrowLeft.keyId: VirtualKey.keyLeft.value,
  LogicalKeyboardKey.arrowRight.keyId: VirtualKey.keyRight.value,
  LogicalKeyboardKey.end.keyId: VirtualKey.keyEnd.value,
  LogicalKeyboardKey.arrowDown.keyId: VirtualKey.keyDown.value,
  LogicalKeyboardKey.pageDown.keyId: VirtualKey.keyPageDown.value,
  LogicalKeyboardKey.insert.keyId: VirtualKey.keyInsert.value,
  LogicalKeyboardKey.delete.keyId: VirtualKey.keyDelete.value,
  LogicalKeyboardKey.metaLeft.keyId: VirtualKey.keyLeftWindows.value,
  LogicalKeyboardKey.metaRight.keyId: VirtualKey.keyRightWindows.value,
  LogicalKeyboardKey.contextMenu.keyId: VirtualKey.keyApplication.value,
  LogicalKeyboardKey.numpadMultiply.keyId: VirtualKey.keyKpMultiply.value,
  LogicalKeyboardKey.numpadAdd.keyId: VirtualKey.keyKpPlus.value,
  LogicalKeyboardKey.numpadSubtract.keyId: VirtualKey.keyKpMinus.value,
  LogicalKeyboardKey.numpadDivide.keyId: VirtualKey.keyKpDivide.value,
  LogicalKeyboardKey.numpadEnter.keyId: VirtualKey.keyKpEnter.value,
  LogicalKeyboardKey.numpadDecimal.keyId: VirtualKey.keyKpDecimal.value,
  LogicalKeyboardKey.numpad1.keyId: VirtualKey.keyKp1.value,
  LogicalKeyboardKey.numpad2.keyId: VirtualKey.keyKp2.value,
  LogicalKeyboardKey.numpad3.keyId: VirtualKey.keyKp3.value,
  LogicalKeyboardKey.numpad4.keyId: VirtualKey.keyKp4.value,
  LogicalKeyboardKey.numpad5.keyId: VirtualKey.keyKp5.value,
  LogicalKeyboardKey.numpad6.keyId: VirtualKey.keyKp6.value,
  LogicalKeyboardKey.numpad7.keyId: VirtualKey.keyKp7.value,
  LogicalKeyboardKey.numpad8.keyId: VirtualKey.keyKp8.value,
  LogicalKeyboardKey.numpad9.keyId: VirtualKey.keyKp9.value,
  LogicalKeyboardKey.numpad0.keyId: VirtualKey.keyKp0.value,
  LogicalKeyboardKey.controlRight.keyId: VirtualKey.keyRightCtrl.value,
  LogicalKeyboardKey.altRight.keyId: VirtualKey.keyRightAlt.value,
};

final Map<int, String?> displayMap = {
  VirtualKey.keyNone.value: "",
  VirtualKey.keyMouseLb.value: "MOUSE_LEFT",
  VirtualKey.keyMouseRb.value: "MOUSE_RIGHT",
  VirtualKey.keyMouseMb.value: "MOUSE_MIDDLe",
  VirtualKey.keyTab.value: LogicalKeyboardKey.tab.keyLabel,
  VirtualKey.keyQ.value: LogicalKeyboardKey.keyQ.keyLabel,
  VirtualKey.keyW.value: LogicalKeyboardKey.keyW.keyLabel,
  VirtualKey.keyE.value: LogicalKeyboardKey.keyE.keyLabel,
  VirtualKey.keyR.value: LogicalKeyboardKey.keyR.keyLabel,
  VirtualKey.keyT.value: LogicalKeyboardKey.keyT.keyLabel,
  VirtualKey.keyY.value: LogicalKeyboardKey.keyY.keyLabel,
  VirtualKey.keyU.value: LogicalKeyboardKey.keyU.keyLabel,
  VirtualKey.keyI.value: LogicalKeyboardKey.keyI.keyLabel,
  VirtualKey.keyO.value: LogicalKeyboardKey.keyO.keyLabel,
  VirtualKey.keyP.value: LogicalKeyboardKey.keyP.keyLabel,
  VirtualKey.keyA.value: LogicalKeyboardKey.keyA.keyLabel,
  VirtualKey.keyS.value: LogicalKeyboardKey.keyS.keyLabel,
  VirtualKey.keyD.value: LogicalKeyboardKey.keyD.keyLabel,
  VirtualKey.keyF.value: LogicalKeyboardKey.keyF.keyLabel,
  VirtualKey.keyG.value: LogicalKeyboardKey.keyG.keyLabel,
  VirtualKey.keyH.value: LogicalKeyboardKey.keyH.keyLabel,
  VirtualKey.keyJ.value: LogicalKeyboardKey.keyJ.keyLabel,
  VirtualKey.keyK.value: LogicalKeyboardKey.keyK.keyLabel,
  VirtualKey.keyL.value: LogicalKeyboardKey.keyL.keyLabel,
  VirtualKey.keyZ.value: LogicalKeyboardKey.keyZ.keyLabel,
  VirtualKey.keyX.value: LogicalKeyboardKey.keyX.keyLabel,
  VirtualKey.keyC.value: LogicalKeyboardKey.keyC.keyLabel,
  VirtualKey.keyV.value: LogicalKeyboardKey.keyV.keyLabel,
  VirtualKey.keyB.value: LogicalKeyboardKey.keyB.keyLabel,
  VirtualKey.keyN.value: LogicalKeyboardKey.keyN.keyLabel,
  VirtualKey.keyM.value: LogicalKeyboardKey.keyM.keyLabel,
  VirtualKey.key1.value: LogicalKeyboardKey.digit1.keyLabel,
  VirtualKey.key2.value: LogicalKeyboardKey.digit2.keyLabel,
  VirtualKey.key3.value: LogicalKeyboardKey.digit3.keyLabel,
  VirtualKey.key4.value: LogicalKeyboardKey.digit4.keyLabel,
  VirtualKey.key5.value: LogicalKeyboardKey.digit5.keyLabel,
  VirtualKey.key6.value: LogicalKeyboardKey.digit6.keyLabel,
  VirtualKey.key7.value: LogicalKeyboardKey.digit7.keyLabel,
  VirtualKey.key8.value: LogicalKeyboardKey.digit8.keyLabel,
  VirtualKey.key9.value: LogicalKeyboardKey.digit9.keyLabel,
  VirtualKey.key0.value: LogicalKeyboardKey.digit0.keyLabel,
  VirtualKey.keyEscape.value: LogicalKeyboardKey.escape.keyLabel,
  VirtualKey.keyMinus.value: LogicalKeyboardKey.minus.keyLabel,
  VirtualKey.keyEquals.value: LogicalKeyboardKey.equal.keyLabel,
  VirtualKey.keyBackspace.value: LogicalKeyboardKey.backspace.keyLabel,
  VirtualKey.keyLeftBracket.value: LogicalKeyboardKey.bracketLeft.keyLabel,
  VirtualKey.keyRightBracket.value: LogicalKeyboardKey.bracketRight.keyLabel,
  VirtualKey.keyEnter.value: "ENTER",
  VirtualKey.keyLeftCtrl.value: "LCTRL",
  VirtualKey.keyComma.value: LogicalKeyboardKey.comma.keyLabel,
  VirtualKey.keyPeriod.value: LogicalKeyboardKey.period.keyLabel,
  VirtualKey.keySlash.value: LogicalKeyboardKey.slash.keyLabel,
  VirtualKey.keyRightShift.value: "RSHIFT",
  VirtualKey.keyLeftAlt.value: "ALT",
  VirtualKey.keySpace.value: "SPACE",
  VirtualKey.keyCapsLock.value: "CAPS",
  VirtualKey.keySemicolon.value: LogicalKeyboardKey.semicolon.keyLabel,
  VirtualKey.keyApostrophe.value: LogicalKeyboardKey.quote.keyLabel,
  VirtualKey.keyGrave.value: LogicalKeyboardKey.backquote.keyLabel,
  VirtualKey.keyLeftShift.value: "LSHIFT",
  VirtualKey.keyBackslash.value: LogicalKeyboardKey.backslash.keyLabel,
  VirtualKey.keyF1.value: LogicalKeyboardKey.f1.keyLabel,
  VirtualKey.keyF2.value: LogicalKeyboardKey.f2.keyLabel,
  VirtualKey.keyF3.value: LogicalKeyboardKey.f3.keyLabel,
  VirtualKey.keyF4.value: LogicalKeyboardKey.f4.keyLabel,
  VirtualKey.keyF5.value: LogicalKeyboardKey.f5.keyLabel,
  VirtualKey.keyF6.value: LogicalKeyboardKey.f6.keyLabel,
  VirtualKey.keyF7.value: LogicalKeyboardKey.f7.keyLabel,
  VirtualKey.keyF8.value: LogicalKeyboardKey.f8.keyLabel,
  VirtualKey.keyF9.value: LogicalKeyboardKey.f9.keyLabel,
  VirtualKey.keyF10.value: LogicalKeyboardKey.f10.keyLabel,
  VirtualKey.keyNumLock.value: LogicalKeyboardKey.numLock.keyLabel,
  VirtualKey.keyScrollLock.value: LogicalKeyboardKey.scrollLock.keyLabel,
  VirtualKey.keyHome.value: LogicalKeyboardKey.home.keyLabel,
  VirtualKey.keyUp.value: LogicalKeyboardKey.arrowUp.keyLabel,
  VirtualKey.keyPageUp.value: LogicalKeyboardKey.pageUp.keyLabel,
  VirtualKey.keyLeft.value: LogicalKeyboardKey.arrowLeft.keyLabel,
  VirtualKey.keyRight.value: LogicalKeyboardKey.arrowRight.keyLabel,
  VirtualKey.keyEnd.value: LogicalKeyboardKey.end.keyLabel,
  VirtualKey.keyDown.value: LogicalKeyboardKey.arrowDown.keyLabel,
  VirtualKey.keyPageDown.value: LogicalKeyboardKey.pageDown.keyLabel,
  VirtualKey.keyInsert.value: LogicalKeyboardKey.insert.keyLabel,
  VirtualKey.keyDelete.value: LogicalKeyboardKey.delete.keyLabel,
  VirtualKey.keyLeftWindows.value: LogicalKeyboardKey.metaLeft.keyLabel,
  VirtualKey.keyRightWindows.value: LogicalKeyboardKey.metaRight.keyLabel,
  VirtualKey.keyApplication.value: LogicalKeyboardKey.contextMenu.keyLabel,
  VirtualKey.keyKpMultiply.value: LogicalKeyboardKey.numpadMultiply.keyLabel,
  VirtualKey.keyKpPlus.value: LogicalKeyboardKey.numpadAdd.keyLabel,
  VirtualKey.keyKpMinus.value: LogicalKeyboardKey.numpadSubtract.keyLabel,
  VirtualKey.keyKpDivide.value: "DIVIDE",
  VirtualKey.keyKpEnter.value: "ENTER",
  VirtualKey.keyKpDecimal.value: LogicalKeyboardKey.numpadDecimal.keyLabel,
  VirtualKey.keyKp1.value: LogicalKeyboardKey.numpad1.keyLabel,
  VirtualKey.keyKp2.value: LogicalKeyboardKey.numpad2.keyLabel,
  VirtualKey.keyKp3.value: LogicalKeyboardKey.numpad3.keyLabel,
  VirtualKey.keyKp4.value: LogicalKeyboardKey.numpad4.keyLabel,
  VirtualKey.keyKp5.value: LogicalKeyboardKey.numpad5.keyLabel,
  VirtualKey.keyKp6.value: LogicalKeyboardKey.numpad6.keyLabel,
  VirtualKey.keyKp7.value: LogicalKeyboardKey.numpad7.keyLabel,
  VirtualKey.keyKp8.value: LogicalKeyboardKey.numpad8.keyLabel,
  VirtualKey.keyKp9.value: LogicalKeyboardKey.numpad9.keyLabel,
  VirtualKey.keyKp0.value: LogicalKeyboardKey.numpad0.keyLabel,
  VirtualKey.keyRightCtrl.value: "RCTRL",
  VirtualKey.keyRightAlt.value: "ALT",
};